# Generated by Django 5.0.6 on 2024-05-09 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('websites', models.CharField(max_length=100, null=True)),
                ('licence', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='club_images')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='False', max_length=100)),
                ('description', models.CharField(default='False', max_length=100)),
                ('fees', models.CharField(default='False', max_length=100)),
                ('img', models.ImageField(null=True, upload_to='sports_images')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('isProfileComplete', models.CharField(default='False', max_length=100)),
                ('isActive', models.CharField(default='False', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFeesPaid', models.CharField(default='False', max_length=100)),
                ('dateOfPayment', models.DateField(null=True)),
                ('dateOfEnroll', models.DateField(null=True)),
                ('dateOfQuit', models.DateField(null=True)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('EnrolledSports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sports')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
